In [1]:
import pandas as pd
 
df = pd.read_csv('../data/raw/hotel_bookings.csv')

df['arrival_date'] = pd.to_datetime(
    df['arrival_date_year'].astype(str) + '-' +
    df['arrival_date_month'] + '-' +
    df['arrival_date_day_of_month'].astype(str)
)
daily = (
    df.groupby('arrival_date')
      .size()
      .reset_index(name='bookings')
)

daily = daily.sort_values('arrival_date').reset_index(drop=True)
daily.head()

  arrival_date  bookings
0   2015-07-01       122
1   2015-07-02        93
2   2015-07-03        56
3   2015-07-04        88
4   2015-07-05        53

In [2]:
# create time based features
daily['day_of_week'] = daily['arrival_date'].dt.dayofweek
daily['is_weekend'] = daily['day_of_week'].isin([5,6]).astype(int)
daily['month'] = daily['arrival_date'].dt.month

In [3]:
daily.head(5)

  arrival_date  bookings  day_of_week  is_weekend  month
0   2015-07-01       122            2           0      7
1   2015-07-02        93            3           0      7
2   2015-07-03        56            4           0      7
3   2015-07-04        88            5           1      7
4   2015-07-05        53            6           1      7

In [4]:
daily['lag_1'] = daily['bookings'].shift(1)
daily['lag_7'] = daily['bookings'].shift(7)

In [5]:
daily['rolling_7'] = daily['bookings'].rolling(window=7).mean()
daily['rolling_14'] = daily['bookings'].rolling(window=14).mean()

In [6]:
daily.head(20)

,arrival_date,bookings,day_of_week,is_weekend,month,lag_1,lag_7,rolling_7,rolling_14
0,2015-07-01,122,2,0,7,NaN,NaN,NaN,NaN
1,2015-07-02,93,3,0,7,122.0,NaN,NaN,NaN
2,2015-07-03,56,4,0,7,93.0,NaN,NaN,NaN
3,2015-07-04,88,5,1,7,56.0,NaN,NaN,NaN
4,2015-07-05,53,6,1,7,88.0,NaN,NaN,NaN
5,2015-07-06,75,0,0,7,53.0,NaN,NaN,NaN
6,2015-07-07,54,1,0,7,75.0,NaN,77.285714,NaN
7,2015-07-08,69,2,0,7,54.0,122.0,69.714286,NaN
8,2015-07-09,80,3,0,7,69.0,93.0,67.857143,NaN
9,2015-07-10,51,4,0,7,80.0,56.0,67.142857,NaN
10,2015-07-11,103,5,1,7,51.0,88.0,69.285714,NaN
11,2015-07-12,63,6,1,7,103.0,53.0,70.714286,NaN
12,2015-07-13,84,0,0,7,63.0,75.0,72.000000,NaN
13,2015-07-14,35,1,0,7,84.0,54.0,69.285714,73.285714
14,2015-07-15,102,2,0,7,35.0,69.0,74.000000,71.857143
15,2015-07-16,103,3,0,7,102.0,80.0,77.285714,72.571429
16,2015-07-17,151,4,0,7,103.0,51.0,91.571429,79.357143
17,2015-07-18,155,5,1,7,151.0,103.0,99.000000,84.142857
18,2015-07-19,54,6,1,7,155.0,63.0,97.714286,84.214286
19,2015-07-20,125,0,0,7,54.0,84.0,103.571429,87.785714

In [7]:
daily.isnull().sum()

arrival_date     0
bookings         0
day_of_week      0
is_weekend       0
month            0
lag_1            1
lag_7            7
rolling_7        6
rolling_14      13
dtype: int64

In [8]:
daily_clean = daily.dropna().reset_index(drop=True)

In [9]:
daily_clean.isnull().sum()

arrival_date    0
bookings        0
day_of_week     0
is_weekend      0
month           0
lag_1           0
lag_7           0
rolling_7       0
rolling_14      0
dtype: int64

In [10]:
features = [
    'day_of_week',
    'is_weekend',
    'month',
    'lag_1',
    'lag_7',
    'rolling_7',
    'rolling_14'
]

target = 'bookings'
X = daily_clean[features]
y = daily_clean[target]

In [11]:
daily_to_save = daily[['arrival_date', 'bookings']]
daily_to_save.to_csv("../data/processed/daily_demand.csv", index=False)

print("Processed demand data saved")

Processed demand data saved

In [12]:
daily_to_save.head(5)

  arrival_date  bookings
0   2015-07-01       122
1   2015-07-02        93
2   2015-07-03        56
3   2015-07-04        88
4   2015-07-05        53